const dependencies = [
    'react-native-dotenv',
    'axios',
    'patch-package',
    'postinstall-postinstall',
  ],
  devDependencies = [
    '@commitlint/cli',
    '@commitlint/config-conventional',
    'cspell',
    'lint-staged',
    'prettier',
    'react-native-svg-transformer',
    'eslint-plugin-unused-imports',
    'eslint-plugin-no-relative-import-paths',
    'eslint-plugin-ft-flow',
    '@svgr/cli',
    'eslint-plugin-react',
    'eslint-plugin-react-native',
    '@babel/eslint-parser',
    'babel-plugin-module-resolver',
    'ts-prune',
    'depcheck',
  ];
module.exports = {devDependencies: devDependencies, dependencies: dependencies};
